apiVersion: v1
kind: Service
metadata:
  name:  sample-flask-service
spec:
  selector:
    app: sample-flask
  type:  NodePort
  ports:
    - name:  name-of-the-port
      port:  80
      targetPort:  5000
      nodePort: 30001